-- Add CRM-owned outbound CTI foundation: seat bindings, call sessions, and audit target types.

ALTER TABLE `operationlog`
  MODIFY `targetType` ENUM(
    'USER',
    'TEAM',
    'ROLE',
    'LEAD',
    'LEAD_IMPORT_BATCH',
    'LEAD_IMPORT_ROW',
    'LEAD_IMPORT_TEMPLATE',
    'LEAD_DEDUP_LOG',
    'LEAD_CUSTOMER_MERGE_LOG',
    'CUSTOMER',
    'LEAD_ASSIGNMENT',
    'FOLLOW_UP_TASK',
    'CALL_RECORD',
    'CALL_RECORDING',
    'CALL_AI_ANALYSIS',
    'CALL_QUALITY_REVIEW',
    'MOBILE_DEVICE',
    'OUTBOUND_CALL_SESSION',
    'OUTBOUND_CALL_SEAT_BINDING',
    'WECHAT_RECORD',
    'LIVE_SESSION',
    'LIVE_INVITATION',
    'ORDER',
    'GIFT_RECORD',
    'SHIPPING_TASK',
    'SUPPLIER',
    'PRODUCT',
    'PRODUCT_SKU',
    'SALES_ORDER',
    'SALES_ORDER_ITEM',
    'SALES_ORDER_GIFT_ITEM',
    'TRADE_ORDER',
    'TRADE_ORDER_ITEM',
    'TRADE_ORDER_ITEM_COMPONENT',
    'PRODUCT_BUNDLE',
    'PRODUCT_BUNDLE_ITEM',
    'SHIPPING_EXPORT_BATCH',
    'SHIPPING_EXPORT_LINE',
    'LOGISTICS_FOLLOW_UP_TASK',
    'COD_COLLECTION_RECORD',
    'PAYMENT_PLAN',
    'PAYMENT_RECORD',
    'COLLECTION_TASK',
    'TAG_GROUP',
    'TAG_CATEGORY',
    'TAG',
    'CATEGORY',
    'DICTIONARY_TYPE',
    'DICTIONARY_ITEM',
    'CALL_RESULT_SETTING',
    'SYSTEM_SETTING'
  ) NOT NULL;

CREATE TABLE `outbound_call_seat_bindings` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `provider` ENUM('MOCK', 'FREESWITCH', 'CUSTOM_HTTP') NOT NULL DEFAULT 'MOCK',
  `seatNo` VARCHAR(191) NOT NULL,
  `extensionNo` VARCHAR(191) NULL,
  `displayNumber` VARCHAR(191) NULL,
  `routingGroup` VARCHAR(191) NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `lastRegisteredAt` DATETIME(3) NULL,
  `metadataJson` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `outbound_call_seat_bindings_userId_key`(`userId`),
  UNIQUE INDEX `outbound_call_seat_bindings_provider_seatNo_key`(`provider`, `seatNo`),
  INDEX `outbound_call_seat_bindings_provider_enabled_idx`(`provider`, `enabled`),
  INDEX `outbound_call_seat_bindings_enabled_updatedAt_idx`(`enabled`, `updatedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `outbound_call_sessions` (
  `id` VARCHAR(191) NOT NULL,
  `callRecordId` VARCHAR(191) NOT NULL,
  `customerId` VARCHAR(191) NOT NULL,
  `salesId` VARCHAR(191) NOT NULL,
  `teamId` VARCHAR(191) NULL,
  `seatBindingId` VARCHAR(191) NULL,
  `provider` ENUM('MOCK', 'FREESWITCH', 'CUSTOM_HTTP') NOT NULL,
  `providerCallId` VARCHAR(191) NULL,
  `providerTraceId` VARCHAR(191) NULL,
  `dialedNumber` VARCHAR(191) NOT NULL,
  `displayNumber` VARCHAR(191) NULL,
  `seatNo` VARCHAR(191) NULL,
  `direction` ENUM('OUTBOUND') NOT NULL DEFAULT 'OUTBOUND',
  `status` ENUM('REQUESTED', 'PROVIDER_ACCEPTED', 'RINGING', 'ANSWERED', 'ENDED', 'FAILED', 'CANCELED') NOT NULL DEFAULT 'REQUESTED',
  `failureCode` VARCHAR(191) NULL,
  `failureMessage` TEXT NULL,
  `requestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `ringingAt` DATETIME(3) NULL,
  `answeredAt` DATETIME(3) NULL,
  `endedAt` DATETIME(3) NULL,
  `durationSeconds` INTEGER NULL,
  `recordingUrl` TEXT NULL,
  `recordingExternalId` VARCHAR(191) NULL,
  `recordingImportedAt` DATETIME(3) NULL,
  `rawCdrJson` JSON NULL,
  `rawEventsJson` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `outbound_call_sessions_callRecordId_key`(`callRecordId`),
  UNIQUE INDEX `outbound_call_sessions_provider_callId_key`(`provider`, `providerCallId`),
  INDEX `outbound_call_sessions_sales_requestedAt_idx`(`salesId`, `requestedAt`),
  INDEX `outbound_call_sessions_customer_requestedAt_idx`(`customerId`, `requestedAt`),
  INDEX `outbound_call_sessions_team_requestedAt_idx`(`teamId`, `requestedAt`),
  INDEX `outbound_call_sessions_seat_requestedAt_idx`(`seatBindingId`, `requestedAt`),
  INDEX `outbound_call_sessions_status_requestedAt_idx`(`status`, `requestedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `outbound_call_seat_bindings` ADD CONSTRAINT `outbound_call_seat_bindings_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `outbound_call_sessions` ADD CONSTRAINT `outbound_call_sessions_callRecordId_fkey` FOREIGN KEY (`callRecordId`) REFERENCES `callrecord`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `outbound_call_sessions` ADD CONSTRAINT `outbound_call_sessions_customerId_fkey` FOREIGN KEY (`customerId`) REFERENCES `customer`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `outbound_call_sessions` ADD CONSTRAINT `outbound_call_sessions_salesId_fkey` FOREIGN KEY (`salesId`) REFERENCES `user`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE `outbound_call_sessions` ADD CONSTRAINT `outbound_call_sessions_teamId_fkey` FOREIGN KEY (`teamId`) REFERENCES `teams`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE `outbound_call_sessions` ADD CONSTRAINT `outbound_call_sessions_seatBindingId_fkey` FOREIGN KEY (`seatBindingId`) REFERENCES `outbound_call_seat_bindings`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
