-- 未接通回流: 公海入池原因与归属事件原因新增 UNREACHABLE_RECYCLE
ALTER TABLE `customer`
    MODIFY `publicPoolReason` ENUM('UNASSIGNED_IMPORT', 'MANUAL_RELEASE', 'INACTIVE_RECYCLE', 'OWNER_LEFT_TEAM', 'BATCH_REALLOCATION', 'MERGE_RELEASE', 'INVALID_FOLLOWUP_RECYCLE', 'UNREACHABLE_RECYCLE') NULL;

ALTER TABLE `customerownershipevent`
    MODIFY `reason` ENUM('UNASSIGNED_IMPORT', 'MANUAL_RELEASE', 'INACTIVE_RECYCLE', 'OWNER_LEFT_TEAM', 'BATCH_REALLOCATION', 'MERGE_RELEASE', 'INVALID_FOLLOWUP_RECYCLE', 'UNREACHABLE_RECYCLE', 'SALES_CLAIM', 'SUPERVISOR_ASSIGN', 'AUTO_ASSIGN', 'TEAM_TRANSFER', 'OWNER_RESTORE') NOT NULL;
